# Generated by Django 5.0.4 on 2026-04-03 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="medical_docs/%Y/%m/%d/")),
                ("file_type", models.CharField(default="pdf", max_length=10)),
                ("file_size_kb", models.PositiveIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(default=0)),
                (
                    "chunk_strategy",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed-size"),
                            ("recursive", "Recursive"),
                            ("semantic", "Semantic"),
                        ],
                        default="recursive",
                        max_length=20,
                    ),
                ),
                ("chunk_size", models.PositiveIntegerField(default=512)),
                ("chunk_overlap", models.PositiveIntegerField(default=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "rag_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("chunk_index", models.PositiveIntegerField()),
                ("page_start", models.PositiveIntegerField(default=0)),
                ("page_end", models.PositiveIntegerField(default=0)),
                ("char_start", models.PositiveIntegerField(default=0)),
                ("char_end", models.PositiveIntegerField(default=0)),
                (
                    "chroma_id",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="models/gemini-embedding-001", max_length=100
                    ),
                ),
                ("is_embedded", models.BooleanField(default=False)),
                ("embedded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="Assistant.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk",
                "verbose_name_plural": "Chunks",
                "db_table": "rag_chunk",
                "ordering": ["document", "chunk_index"],
                "unique_together": {("document", "chunk_index")},
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-generated from first message or set by user.",
                        max_length=255,
                    ),
                ),
                (
                    "top_k_retrieval",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="How many chunks to fetch from ChromaDB before re-ranking.",
                    ),
                ),
                (
                    "top_k_rerank",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="How many chunks to pass to Gemini after re-ranking.",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(default="gemini-1.5-flash", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Documents to restrict RAG retrieval to. Empty = all documents.",
                        related_name="chat_sessions",
                        to="Assistant.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "db_table": "rag_chat_session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "retrieval_scores",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {chunk_id, similarity_score, rerank_score} dicts.",
                    ),
                ),
                ("was_streamed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="Assistant.chatsession",
                    ),
                ),
                (
                    "source_chunks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Chunks retrieved and used to generate this response.",
                        related_name="cited_in_messages",
                        to="Assistant.chunk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "rag_message",
                "ordering": ["session", "created_at"],
            },
        ),
    ]
